create app structure, add postgres in docker and entities USES & TOKEN
lae1965/go-video-hosting pull request #1
Opened 2024-09-24 08:43 UTC by lae1965

2024-09-26 14:17 UTC, kar-pev requested changes

2024-09-26 14:17 UTC, kar-pev commented on .env
> +DB_PASSWORD=lae1965
Лучше такое хранить как env параметры командной строки

2024-09-26 14:17 UTC, kar-pev commented on cmd/main.go
> +	db, err := repository.NewPostgresDB(repository.Config{
такое, наверное, лучше вызвать отдельным методом, в который передавать весь конфиг или только  db, чтобы мэйн не рос по объему

2024-09-26 14:17 UTC, kar-pev commented on cmd/main.go
> +		logrus.Fatalf("Failed to installation db: %s", err.Error())
Тут бы надо падать, тк нет смысла запускать сервис без доступа к базе

2024-09-26 14:17 UTC, kar-pev commented on cmd/main.go
> +		logrus.Fatalf("Error initialization config: %s", err.Error())
Тут надо падать, тк нет переменной (вроде Fatalf не вызывает exit или return из main)

2024-09-26 14:17 UTC, kar-pev commented on cmd/main.go
> +		logrus.Fatalf("Error loading env variables: %s", err.Error())
Аналогично тому, что выше

2024-09-26 14:17 UTC, kar-pev commented on cmd/main.go
> +	if err := srv.Run(viper.GetString("port"), handlers.InitRoutes()); err != nil {
Надо проверить, что переменные существуют, либо задать дефолтное значение при отсутствии

2024-09-26 14:17 UTC, kar-pev commented on configs/config.yml
> +  password: lae1965
Дублирование пароля(его бы, по хорошему, вообще нигде не писать)

2024-09-26 14:17 UTC, kar-pev commented on internal/server/server.go
> +		Addr:           ":" + port,
Лучше через fmt

2024-09-26 14:17 UTC, kar-pev commented on pkg/model/token.go
> +	Id     int    `json:"-"`
не уверен, что строит так делать (расскажи, в чем была идея такого значения в json)

2024-09-26 14:17 UTC, kar-pev commented on pkg/model/user.go
> +	Id              int       `json:"-"`
Аналогично вопросу ранее

2024-09-26 14:17 UTC, kar-pev commented on pkg/repository/postgres.go
> +	db, err := sqlx.Open("postgres", fmt.Sprintf("host=%s port=%s user=%s dbname=%s password=%s sslmode=%s", cfg.Host, cfg.Port, cfg.Username, cfg.DBName, cfg.Password, cfg.SSLMode))
напиши в несколько строк, а то нечитаемо

2024-09-26 14:17 UTC, kar-pev commented on pkg/repository/postgres.go
> +	err = db.Ping()
можно в одну строку объединить

2024-09-26 14:17 UTC, kar-pev commented on pkg/repository/user_posgres.go
> +	row := userPostgres.db.QueryRow("INSERT INTO USERS (nickName, email, passwordHash) values ($1, $2, $3) RETURNING id", user.NickName, user.Email, user.Password)
тут бы тоже как-то визуально получше написать

2024-09-26 14:17 UTC, kar-pev commented on pkg/service/user.go
> +const salt = "sdaf54jfbjbjyjb6bnaSldHNVV8d0qwjeh"
Такое тоже, вероятно, не стоит хранить в коде

2024-09-26 14:17 UTC, kar-pev commented on run-migrate.sh
> +migrate -path ./schema -database "postgresql://postgres:lae1965@localhost:5436/go_video_hosting?sslmode=disable" -verbose up
аналогично про пароль

2024-09-27 06:11 UTC, lae1965 commented on cmd/main.go
> +	db, err := repository.NewPostgresDB(repository.Config{
В смысле вынести инициализацию db в отдельную функцию в этом же файле?

2024-09-27 06:12 UTC, lae1965 commented on .env
> +DB_PASSWORD=lae1965
А почему лучше? Тогда файл sh что ли написать для запуска приложения?

2024-09-27 06:13 UTC, lae1965 commented on cmd/main.go
> +		logrus.Fatalf("Failed to installation db: %s", err.Error())
Проверю, если Fatalf не роняет, тогда добавлю.

2024-09-27 06:13 UTC, lae1965 commented on cmd/main.go
> +		logrus.Fatalf("Error initialization config: %s", err.Error())
Ок

2024-09-27 06:14 UTC, lae1965 commented on cmd/main.go
> +		logrus.Fatalf("Error loading env variables: %s", err.Error())
Ок

2024-09-27 06:17 UTC, lae1965 commented on pkg/model/token.go
> +	Id     int    `json:"-"`
Тут я просто тупо списал у Жашкевича. Я еще до конца не разобрался с темой про теги. Зачем они нужны - понял. Но кто в какой момент и как использует тег json - не понимаю.

2024-09-27 06:18 UTC, lae1965 commented on pkg/model/user.go
> +	Id              int       `json:"-"`
?

2024-09-27 06:19 UTC, lae1965 commented on run-migrate.sh
> +migrate -path ./schema -database "postgresql://postgres:lae1965@localhost:5436/go_video_hosting?sslmode=disable" -verbose up
ну этот файл же рабочий, он в прод не пойдет. Он просто для удобства. Все равно надо?

2024-09-27 14:35 UTC, kar-pev commented on cmd/main.go
> +	db, err := repository.NewPostgresDB(repository.Config{
В идеале унести это к логике взаимодействия с бд и там создать конструкор `connection`а к базе, который принимает конфиг

2024-09-27 14:36 UTC, kar-pev commented on .env
> +DB_PASSWORD=lae1965
Почему лучше: ты не выкладываешь пароли в опенсорс. Как сделать: глобально, сервис должен запускаться в докерфайле, в окружение которого нужно прокидывать пароли(если через кубер, то там для этого отдельный конфиг есть), но пока можно локальный скрипт написать, да(заливать его, соответственно, не надо)

2024-09-27 14:38 UTC, kar-pev commented on pkg/model/token.go
> +	Id     int    `json:"-"`
Это используется при сереализации конфига в `json` объект(или, вроде, в модель/структуру). Если тебе не нужен id в структуре, то можно писать название с маленькой буквы, но это, вероятно, не так, так что пиши просто  id, если на то нет каких-то конкретных причин

2024-09-27 14:39 UTC, kar-pev commented on pkg/model/user.go
> +	Id              int       `json:"-"`
Тут то же замечание, что и [здесь](https://github.com/lae1965/go-video-hosting/pull/1#discussion_r1777163690)

2024-09-27 14:39 UTC, kar-pev commented on run-migrate.sh
> +migrate -path ./schema -database "postgresql://postgres:lae1965@localhost:5436/go_video_hosting?sslmode=disable" -verbose up
Тогда не стоит заливать его в репозиторий)

2024-09-27 18:57 UTC, lae1965 commented on cmd/main.go
> +		logrus.Fatalf("Failed to installation db: %s", err.Error())
Само падает

2024-09-27 18:57 UTC, lae1965 commented on cmd/main.go
> +		logrus.Fatalf("Error initialization config: %s", err.Error())
Само падает

2024-09-27 18:58 UTC, lae1965 commented on cmd/main.go
> +		logrus.Fatalf("Error loading env variables: %s", err.Error())
Само падает

2024-09-27 18:59 UTC, lae1965 commented on cmd/main.go
> +	if err := srv.Run(viper.GetString("port"), handlers.InitRoutes()); err != nil {
Ты имеешь в виду port? А как она может не существовать? Я же ее определил.

2024-09-27 19:00 UTC, lae1965 commented on configs/config.yml
> +  password: lae1965
Убрал. Раньше хотел, но забыл.

2024-09-27 19:01 UTC, lae1965 commented on pkg/model/token.go
> +	Id     int    `json:"-"`
Ок

2024-09-27 19:01 UTC, lae1965 commented on pkg/model/user.go
> +	Id              int       `json:"-"`
Поправлю

2024-09-27 19:02 UTC, lae1965 commented on pkg/repository/postgres.go
> +	db, err := sqlx.Open("postgres", fmt.Sprintf("host=%s port=%s user=%s dbname=%s password=%s sslmode=%s", cfg.Host, cfg.Port, cfg.Username, cfg.DBName, cfg.Password, cfg.SSLMode))
Сделал

2024-09-27 19:02 UTC, lae1965 commented on pkg/repository/postgres.go
> +	err = db.Ping()
Сделал

2024-09-27 19:02 UTC, lae1965 commented on pkg/repository/user_posgres.go
> +	row := userPostgres.db.QueryRow("INSERT INTO USERS (nickName, email, passwordHash) values ($1, $2, $3) RETURNING id", user.NickName, user.Email, user.Password)
Сделал

2024-09-27 19:03 UTC, lae1965 commented on pkg/service/user.go
> +const salt = "sdaf54jfbjbjyjb6bnaSldHNVV8d0qwjeh"
Убрал в .env

2024-09-27 19:03 UTC, lae1965 commented on run-migrate.sh
> +migrate -path ./schema -database "postgresql://postgres:lae1965@localhost:5436/go_video_hosting?sslmode=disable" -verbose up
Ok

2024-09-27 19:11 UTC, lae1965 commented on internal/server/server.go
> +		Addr:           ":" + port,
Поправил

2024-09-29 17:16 UTC, lae1965 commented on cmd/main.go
> +	db, err := repository.NewPostgresDB(repository.Config{
А если приложение вырастет до микросервисов и нескольких баз? Из майна просто вызывать метод инициализации всех баз, которые есть в проекте? Или присвоить каждой базе свой алиас и инициализировать передавая его из майн в метод?

2024-09-30 11:35 UTC, kar-pev commented on cmd/main.go
> +	db, err := repository.NewPostgresDB(repository.Config{
В таком случае, вероятно, захотся разделять сущности баз, тк они отвечают за разный функционал. Вероятно, надо будет просто вызвать несколько раз метод конфигурации, но уже в оберточной функции конфигурации баз, те в мейне будет вызов конфигурации всех баз

2024-09-30 11:37 UTC, kar-pev commented on cmd/main.go
> +	if err := srv.Run(viper.GetString("port"), handlers.InitRoutes()); err != nil {
Ну это ты ее в конфиге определил, но, может так случиться, что ты ее удалишь из конфига или кто-то еще будет конфиг редачить, из-за чего порта там не будет. Такое стоит учитывать

2024-09-30 11:47 UTC, lae1965 commented on cmd/main.go
> +	if err := srv.Run(viper.GetString("port"), handlers.InitRoutes()); err != nil {
Сделал

2024-09-30 12:20 UTC, merged